Improve error handling

diff --git a/bin/import_secret b/bin/import_secret
--- a/bin/import_secret
+++ b/bin/import_secret
@@ -5,7 +5,10 @@ main() {
     local source_file="${2:?Source file is required}"
     local secrets_dir="${SECRETS_DIR:-./secrets}"
 
-    mkdir -p "${secrets_dir}"
+    mkdir -p "${secrets_dir}" || {
+        printf "Error: Cannot create secrets dir '%s'" "${secrets_dir}" >&2
+        return 1
+    }
 
     if [[ ! -f "${source_file}" ]]; then
         printf "%s: Source file doesn't exist, is unreadable or is not a valid file\n" "${source_file}" >&2
@@ -15,13 +18,20 @@ main() {
     local secret_file="${secrets_dir}/${secret_name}"
 
     if [[ -f "${secret_file}" ]]; then
-        printf "Warning: Secret file %s already exists.\n" "${secret_file}" >&2
+        printf "Warning: Secret file '%s' already exists.\n" "${secret_file}" >&2
         printf "Press CTRL+C to abort...\n" >&2
         printf "Waiting 10 seconds\n" >&2
         sleep 10
     fi
 
-    cp -v "${source_file}" "${secret_file}"
+    cp -v "${source_file}" "${secret_file}" || {
+        printf "Error: Failure importing secret '%s' from '%s'\n" "${secret_name}" "${source_file}" >&2
+        return 1
+    }
+
+    chmod 0600 "${secret_file}"
+
+    printf "Secret '%s' imported\n" "${secret_name}"
 }
 
 main "$@"
