Wrap in main() function

diff --git a/rootfs/etc/cont-init.d/10-prepare-sshkey b/rootfs/etc/cont-init.d/10-prepare-sshkey
--- a/rootfs/etc/cont-init.d/10-prepare-sshkey
+++ b/rootfs/etc/cont-init.d/10-prepare-sshkey
@@ -1,22 +1,27 @@
 #!/usr/bin/env sh
 
-set -e
+main() {
+    echo "> Preparing ssh keyfile"
 
-if [ ! -f "/secret/keyfile" ]; then
-  echo "> Error: Couldn't locate private key file"
-  exit 1
-fi
+    if [ ! -f "/secret/keyfile" ]; then
+        echo "> Error: Couldn't locate private key file"
+        return 1
+    fi
 
-# Prepare ssh keyfile
-cp "/secret/keyfile" "/app/.ssh/keyfile"
-chmod 0600 /app/.ssh/keyfile
+    # Prepare ssh keyfile
+    cp "/secret/keyfile" "/app/.ssh/keyfile"
+    chmod 0600 /app/.ssh/keyfile
 
-if [ -f "/secret/keyfile-cert" ]; then
-  echo "> Certificate file found. Enabling"
-  cp "/secret/keyfile-cert" "/app/.ssh/keyfile-cert"
-  chmod 0600 "/app/.ssh/keyfile-cert"
-fi
+    if [ -f "/secret/keyfile-cert" ]; then
+        echo "> Certificate file found. Enabling"
+        cp "/secret/keyfile-cert" "/app/.ssh/keyfile-cert"
+        chmod 0600 "/app/.ssh/keyfile-cert"
+    fi
 
-attr /app/ true tunnel:tunnel 0770 2771
+    attr /app/ true tunnel:tunnel 0770 2771
 
-exit 0
+    return $?
+}
+
+main "$@"
+exit $?
